language: node_js
sudo: false
cache:
  directories:
    - node_modules
before_script:
- npm run init
- npm run build
before_deploy:
- npm run zip
deploy:
  provider: releases
  api_key:
    secure: x4lu1Haj0E3nKAck+Z4JTk2Z9AjnfpB6IiUmnicYTjmvqMzOHzwpF59DHNg5mTMlVy+hH4cDUUjvGnNDjhdvR4hLMAA6Rj3y0sjn7iUSDAgsnpbUvnFShMFBA+b6BrthwpNS3RN/rNrXNvsxZDAsYatz9T3Psamp2RpcqJBLiLUeh/AluFdPSwl5LHJ91ZWQAuaFX3Hp7O/ZIOCRDc/tlnyrVXozC+mM7OP9h8y+my4jqtyNMaSoWuxrogprfcfNbws0IJHkAm0jWTKbiSWuH7LkAhhYKnQI/InZRWhibe79yjtzAt0HPbu6uDUv6tpjrhfqI70a58jVfa5AlbPgzas4yfzHaEzCwM1pYznAJ5wgc/PRPF9nxyHjCIlOcZGbKACsa2/aZ14xBX/kJX1WyO5M4PaTnTmksErNpGjnANXyxrEv9UzXe7Y/WWeTtjks/2g9P+KcKnRbMZ3msnIcJcWXJwq//iAM8dUcg1Bjni1j5p4Clp0Jx07zEwRVbC05IgRGUQEKsfJUN2w5a3MJ8G0pbEWBrdNyzwpIRMyJ8Zm3us5bPsPPOjkuzlSkY1ZCZtkcBYQjB1tgeGVJTfSlDPBlgvI4AqTTtYh/1+ih3+idlsu3BK+j42PlixGuWe3X0QOnnY3BWa/Mybw5N4PGliKdzDyVXmCWjLvMzDBF27s=
  file: public.zip
  all_branches: true
  skip_cleanup: true
  on:
    tags: true
    repo: cat-in-136/issue-maps-classic
after_script:
- npm run clean
notifications:
  email: false
  slack:
    secure: YRwS9nxwTpX9JF56lhrcJGJnK/FPepZzAPLajqDKtopvXerso84EnP6gRtBrsywpKJgwMHIOVlsyNZQry/OaPMEy1ajcKEzxQxX/mTi4tbis5iJm+wg1z7g8Gp2peBQzD6ok8xQtuE/8KrxxfDbYGIE+Z+pMGoO9U9h7Fd49zbxje8jGTuQd5gR3ErQAhwvIgCzA3VIA4yCpT374mOOku+FSR1jCthKKhX1Nw/VnspjaFRMvTv7vh0NlQMa/Fx9szCV4dCpFC0pzzDFW10ovIjUI5PrbkbO4Q3gS0StBxAxUi6E1/SQdQOudQk9agwkl2/tjl4rlwTs0sR8M4bCWaTDgskORjDzxKlZmppt/8tXaD/qKjZSbO1Ik7Fv/JPLHpCNJd1spCa1ohmBeBN8OBt8R/61AcWGeW44nSSiWj3a+U3GVLZmxQ/RMJ4bsJ7PL1ZnQLAfoeHtikHjXJJ3ncSVH79jwRWq9+I0os0fJdMAAK7/Ovtb+4ZI1Mv6FVb/GwMRxBmgRGpwfe/Xiu5p+N4HS7HRuNCjjvFCk79Ft1ED8Hz6WWDM/D/8v/LK+E3Bgpgiv0Ap1bZTPIsp8I5j5fnUx8v1ZgvJfoA8t7sxvWIYw0KmJR/XkSvaM5uOlP7deuwCEBEEyXKAGf3t0OMESXiJmCgrLqTSY0kgig6zidAE=
